#!/bin/bash

PATH_PWD=$(pwd)
SCRIPT_PATH=$(dirname $(realpath $0))
SCRIPT_NAME=$(basename $(realpath $0))

# Tools are in same path?
INSTALL_PATH=$(dirname $(realpath -s $0))
PHPEACH_TOOLS_PATH=$([ -e ${INSTALL_PATH}/phing ] && echo ${INSTALL_PATH})
if [[ "$PHPEACH_TOOLS_PATH" == "" ]]; then
    PHPEACH_TOOLS_PATH=${SCRIPT_PATH}/vendor/bin
fi

# Initialize
STATUS_CODE=0

# Come on...
echo -e "\n-=[ Code Quality Builder ]=-\n"

${PHPEACH_TOOLS_PATH}/phing -f ${SCRIPT_PATH}/build.xml -Dproject.basedir=${PATH_PWD} -Dphpqa.tools.path=${PHPEACH_TOOLS_PATH}  $*

exit $STATUS_CODE
