#!/bin/bash

PATH_PWD=$(pwd)
SCRIPT_PATH=$(dirname $(realpath $0))
SCRIPT_NAME=$(basename $(realpath $0))

# Tools are in same path?
INSTALL_PATH=$(dirname $(realpath -s $0))
PHPEACH_TOOLS_PATH=$([ -e ${INSTALL_PATH}/phpcs ] && echo ${INSTALL_PATH}/)

# Setup config, please...
source ${SCRIPT_PATH}/phpeach.conf.dist && \
source ${PATH_PWD}/phpeach.conf.dist 2> /dev/null && \
source ${PATH_PWD}/phpeach.conf 2> /dev/null

# Tools are under vendors deploy?
if [[ "$PHPEACH_TOOLS_PATH" == "" ]]; then
    PHPEACH_TOOLS_PATH=${PATH_PWD}/vendor/bin/
    PHPEACH_TOOLS_PATH=$([ -e ${PHPEACH_TOOLS_PATH}phpcs ] && echo ${PHPEACH_TOOLS_PATH})
fi
if [[ "$PHPEACH_TOOLS_PATH" != "" ]]; then
    PHPEACH_TOOLS_PATH=${PHPEACH_TOOLS_PATH%/}/
fi

if [[ "$1" == "-b" || "$1" == "--build" ]]; then
    shift

    ${PHPEACH_TOOLS_PATH}/phing -f ${SCRIPT_PATH}/build.xml -Dproject.basedir=${PATH_PWD} -Dphpqa.tools.path=${PHPEACH_TOOLS_PATH} $*
    STATUS_CODE=$?

    exit $STATUS_CODE
elif [[ "$1" == "-i" || "$1" == "--install" ]]; then
    shift

    [ ! -e ${PWD}/build.ini.dist ] && cp ${SCRIPT_PATH}/build.ini.dist ${PATH_PWD}
    [ ! -e ${PWD}/phpeach.conf.dist ] && cp ${SCRIPT_PATH}/phpeach.conf.dist ${PATH_PWD}

    exit 0
fi

# Initialize
STATUS_CODE=0
function check_failed() { STATUS_CODE=$1; }
function check_is_ok() { [ $STATUS_CODE -eq 0 ]; return $?; }
function check_is_active() { local TOOL=PHPEACH_ACTIVE_$1; [ ! ${!TOOL=1} -eq 0 ]; return $?; }

# Come on...
echo -e "\n-=[ Code Quality Review ]=-\n"

# Get files to checkup
LIST_FILES=$*
[ "$LIST_FILES" == "" ] && echo "No files to check" && check_failed -1

# Lint php
if check_is_ok && check_is_active SYNTAX; then
    echo -e "Checking syntax errors..."

    for PHP_SCRIPT in $LIST_FILES; do
        if ! php -l ${PHP_SCRIPT} > /dev/null; then
            echo "Errors parsing ${PHP_SCRIPT}"
            check_failed 1
        fi
    done
fi

# Coding Standard Fixer
if check_is_ok && check_is_active FIXER; then
    echo -e "\nChecking code to fix..."

    for PHP_SCRIPT in $LIST_FILES; do
        ${PHPEACH_TOOLS_PATH}php-cs-fixer fix --dry-run ${PHPEACH_FIXER_OPTIONS} ${PHP_SCRIPT} | grep -iv "fixed all files"
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
            check_failed 2
        else
            echo ${PHP_SCRIPT}...Ok
        fi
    done
    if ! check_is_ok; then
        echo -e "\nRun this command for each file to fix it..."
        echo -e ${PHPEACH_TOOLS_PATH}php-cs-fixer fix ${PHPEACH_FIXER_OPTIONS} "<file>\n"
    fi
fi

# Code Sniffer
if check_is_ok && check_is_active PSR; then
    echo -e "\nChecking code style..."

    for PHP_SCRIPT in $LIST_FILES; do
        if ! ${PHPEACH_TOOLS_PATH}phpcs ${PHPEACH_CS_OPTIONS} --standard=${PHPEACH_CODE_STANDARD} ${PHP_SCRIPT}; then
            check_failed 4
        fi
    done
fi

# Mess Detector
if check_is_ok && check_is_active MESSCODE; then
    echo -e "\nChecking code mess..."

    for PHP_SCRIPT in $LIST_FILES; do
        ${PHPEACH_TOOLS_PATH}phpmd ${PHP_SCRIPT} text ${PHPEACH_MESS_RULESET} | grep -v "^$"
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
            check_failed 8
        fi
    done
fi

# Tests
if check_is_ok && check_is_active TESTS; then

    echo -e "\nRunning tests..."

    if ! ${PHPEACH_TOOLS_PATH}phpunit --bootstrap ${PHPEACH_PHPUNIT_BOOTSTRAP} ${PHPEACH_PHPUNIT_OPTS} ${PHPEACH_PHPUNIT_TESTS}; then
        check_failed 16
    fi
fi

# Specs
if check_is_ok && check_is_active SPECS; then

    echo -e "\nRunning specifications..."

    if ! ${PHPEACH_TOOLS_PATH}phpspec  run --no-code-generation --bootstrap=${PHPEACH_PHPSPEC_BOOTSTRAP} ${PHPEACH_PHPSPEC_OPTS} ${PHPEACH_PHPSPEC_SPECS}; then
        check_failed 32
    fi
fi

# Finally...
if check_is_ok; then
    echo -e "\nEverything is ok, congratulations... \(^o^)/ \n"
else
    echo -e "\nSomething was wrong, fixed and try it again... _(¬_¬)- \n"
fi

exit $STATUS_CODE
